apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      volumes:
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data
      containers:
        - image: grafana/grafana-enterprise:10.1
          name: grafana
          ports:
          - containerPort: 8086
          volumeMounts:
            - name: grafana-data
              mountPath: /var/lib/grafana
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
spec:
  ports:
  - port: 8086
    targetPort: 8086
  selector:
    app: influxdb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
