apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      volumes:
      - name: kibana-data
        persistentVolumeClaim:
          claimName: kibana-data
      containers:
        - image: docker.elastic.co/kibana/kibana:8.10.4
          name: kibana
          ports:
          - containerPort: 5601
          volumeMounts:
            - name: kibana-data
              mountPath: /usr/share/kibana/data
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  ports:
  - port: 5601
    targetPort: 5601
  selector:
    app: kibana
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kibana-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
